;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-insert
	evil-insert-line
	hydra-multiple-cursors/mc/edit-lines-and-exit
	hydra-multiple-cursors/mc/insert-letters-and-exit
	hydra-multiple-cursors/mc/mark-next-like-this
	mc/toggle-cursor-on-click
	))

(setq mc/cmds-to-run-once
      '(
	))
